FROM node:lts-alpine AS appbuild
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# RUN npm run build    # tsc

# ----------------------------------------

FROM node:lts-alpine
WORKDIR /app
COPY --from=appbuild /app/ ./app
EXPOSE 3000
CMD npm run prod

