version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      - /app/node_modules
    ports:
      - "80:3000"
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
