apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      targetPort: 27017       # container port
      port: 27017             # for inside the cluster access
