apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      targetPort: 3000       # container port
      port: 80             # for inside the cluster access
      nodePort: 30010      # on node



