apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-depl
  labels:
    app: web
  Namespace: proj1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: siyahatami/proj1:image_tag
        ports:
        - containerPort: 3000
