
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap-depl
  labels:
    app: zap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
      - name: zap
        image: owasp/zap2docker-stable
        command: ['zap.sh', '-c', '-daemon -port 8090 -host 0.0.0.0']
              # zap.sh -daemon -port 8090 -host 0.0.0.0
        ports:
          - containerPort: 8090
        


---
apiVersion: v1
kind: Service
metadata:
  name: zap
spec:
  type: NodePort
  selector:
    app: zap
  ports:
    - protocol: TCP
      targetPort: 8090       # container port
      port: 80             # for inside the cluster access
      nodePort: 30890      # on node


