name: proj1 for nodejs

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
            # echo "Log level: ${{ github.event.inputs.logLevel }}"




env:
  RELEASE_REVISION: "pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}"
  # KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  KUBE_NAMESPACE: proj1


jobs:                                            
  release:                                       
    name: Release                                
    runs-on: ubuntu-latest                       
    steps:                                       
      - name: Cancel Previous Runs               
        uses: styfle/cancel-workflow-action@0.4.1
        with:                                    
          access_token: ${{ github.token }} 
      
      - name: Checkout
        id: chackout                        
        uses: actions/checkout@v2                       
        with:                                           
          ref: ${{ github.event.pull_request.head.sha }}
          # submodules: recursive
  
      # - name: my test command
      #   env:
      #     AUTHOR_NAME: "siamak"
      #     # AUTHOR_NAME: ${{ steps.author.outputs.author }}
      #   run: |
      #     pwd
      #     ls -ld .
      #     ls -l
      #     echo "the author is: $AUTHOR_NAME"
      




      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test
      



      - name: my test command2
        run: |
          for each in ${{ steps.author.outputs.*}}
          do
            echo "$each"
          done
